version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/venv  # Exclude venv from volume mount
    environment:
      - PYTHONPATH=/app
    env_file:
      - ./backend/.env
    restart: unless-stopped
    # For development with hot reload
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload