#!/bin/bash

echo "Firebase is already configured with the following settings:"
echo "- Project: medlegaldoc-b31df"
echo "- Firestore rules: firestore.rules"
echo "- Storage rules: storage.rules"
echo "- Hosting directory: my-vite-react-app/dist"
echo ""
echo "To complete setup, run these commands:"
echo ""
echo "1. Deploy Storage rules:"
echo "   firebase deploy --only storage"
echo ""
echo "2. Deploy Firestore rules:"
echo "   firebase deploy --only firestore"
echo ""
echo "3. Build and deploy the frontend:"
echo "   cd my-vite-react-app"
echo "   npm run build"
echo "   cd .."
echo "   firebase deploy --only hosting"
echo ""
echo "4. To deploy everything at once:"
echo "   firebase deploy"