version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.chainguard
    image: backend-app-chainguard:latest
    container_name: backend-app-chainguard
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8080
      - GOOGLE_CLOUD_PROJECT=medlegaldoc-b31df
      # Add your other environment variables here
      # - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      # etc.
    
    volumes:
      - ~/.config/gcloud:/home/nonroot/.config/gcloud:ro
    
    # Enhanced security options for HIPAA compliance
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined  # May need custom profile for FFmpeg
    
    # Drop all capabilities and add only what's needed
    cap_drop:
      - ALL
    cap_add:
      - CHOWN  # For temporary file creation
      - DAC_OVERRIDE  # For file access
      - SETUID  # For user switching if needed
      - SETGID  # For group switching if needed
    
    # Read-only root filesystem with specific writable mounts (temporarily disabled for testing)
    # read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=200M
      - /tmp/weasyprint_cache:exec,nosuid,size=100M  # WeasyPrint needs exec for font cache
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Restart policy
    restart: unless-stopped
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Optional: Add network isolation
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: backend_bridge